### ISSUE TITLE
Failed to activate the tool-bar-almighty package

### ISSUE THREAD

**Issue by agrublev** [varemenos/atom-toolbar-almighty#28]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [tool-bar-almighty](https://github.com/varemenos/atom-toolbar-almighty) package 0.8.2

### Stack Trace

Failed to activate the tool-bar-almighty package

```
At entries.filter is not a function

TypeError: entries.filter is not a function
    at Object.utils.populate (/packages/tool-bar-almighty/lib/utils.coffee:46:30)
    at Object.toolBarAlmighty.consumeToolBar (/packages/tool-bar-almighty/lib/tool-bar-almighty.coffee:25:9)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:456:81)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:258:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
atom-browsersync 0.2.0 
atom-formatter-jsbeautify 1.1.2 
atom-ide-ui 0.7.0 
atom-pair 2.0.13 
atom-shell-commands 1.5.0 
auto-indent 0.5.0 
autocomplete-html-entities 0.2.0 
better-less 0.4.3 
busy-signal 1.4.3 
color-picker 2.2.5 
dbclick-tree-view 1.6.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.14 
goto 1.8.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
jsformat 0.9.3 
jump-to-import 3.6.5 
language-babel 2.81.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
navigate 0.1.17 
nuclide-format-js 0.0.43 
php-cs-fixer 4.1.1 
php-integrator-autocomplete-plus 1.6.1 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
refactor 0.11.5 
script 3.17.3 
sync-settings 0.8.3 
teletype 0.4.0 
todo-show 2.1.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
```

**Comment by varemenos** [comment]
Hello Angel thank you for reporting this issue. Could you provide me with some info on how to reproduce this issue? 

* I'm interested in the package's configuration (can be found in your config folder, in a file that should be named `config.cson`).
* Did you use this package with older versions of Atom (v1.22 and below) or is this the first time installing the package?

**Comment by agrublev** [comment]
I think I fixed it, i messed around with files i shouldnt :(

**Comment by varemenos** [comment]
That's good to hear, if the issue returns feel free to reopen the issue.
